myproject/core/urls.py
from django.urls import path
from myproject.core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
    path('api/event/add/', v.event_add, name='event_add'),
    path('event/<int:pk>/', v.event_detail, name='event_detail'),
    path('event/<int:pk>/report/', v.event_report, name='event_report'),
]

myproject/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('', include('myproject.core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models


class Event(models.Model):
    title = models.CharField('nome do evento', max_length=200)
    executive_summary = models.TextField('Sumário Executivo')
    institution_history = models.TextField('Histórico da Instituição')
    sport_history = models.TextField(
        'Histórico da modalidade / conceito do projeto')
    date = models.DateField('data do evento')
    estimated_audience = models.PositiveIntegerField('público estimado')
    location = models.TextField('local do evento')
    start = models.TimeField('horário do evento')
    objective = models.TextField('objetivo')
    subscription = models.TextField('inscrição')
    payment = models.TextField('forma de pagamento')
    positive_image = models.TextField('Imagem positiva x imagem corporativa')
    partners = models.TextField('parceiros', help_text='parceiros do projeto')
    description = models.TextField('custo x beneficio')
    target_audience = models.TextField('público-alvo')
    marketing = models.TextField('estratégias de marketing')
    benefits = models.TextField('vantagens para o patrocinador')

    class Meta:
        ordering = ('title',)
        verbose_name = 'evento'
        verbose_name_plural = 'eventos'

    def __str__(self):
        return self.title

    def get_total(self):
        qs = self.proposal_events.filter(event=self.pk)\
            .values_list('value', 'quantity') or 0
        t = 0 if isinstance(qs, int) else sum(map(lambda q: q[0] * q[1], qs))
        return t


class Cost(models.Model):
    sponsorship = models.CharField(
        'patrocínio',
        max_length=100,
        help_text='Inserir o nome da cota'
    )
    value = models.DecimalField('valor', max_digits=8, decimal_places=2)
    reciprocity = models.TextField('reciprocidade')
    event = models.ForeignKey(
        'Event',
        related_name='events',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('event', 'sponsorship',)
        verbose_name = 'custo'
        verbose_name_plural = 'custos'

    def __str__(self):
        return f'{self.event} - {self.sponsorship}'


class Proposal(models.Model):
    description = models.CharField('descrição', max_length=50)
    value = models.DecimalField('valor unit.', max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField('quantidade', default=1)
    event = models.ForeignKey(
        'Event',
        related_name='proposal_events',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def get_subtotal(self):
        if self.value and self.quantity:
            return self.value * self.quantity
        return 0

    subtotal = property(get_subtotal)

    class Meta:
        ordering = ('description',)
        verbose_name = 'orçamento'
        verbose_name_plural = 'orçamentos'

    def __str__(self):
        return f'{self.event} - {self.description}'


class Talk(models.Model):
    '''
    Programação do evento
    '''
    date = models.DateField('data')
    start = models.TimeField('hora')
    description = models.TextField('atividade')
    event = models.ForeignKey(
        'Event',
        related_name='talk_events',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('pk',)
        verbose_name = 'atividade'
        verbose_name_plural = 'atividades'

    def __str__(self):
        return f'{self.event} - {self.description}'

myproject/core/forms.py
from django import forms
from .models import Event, Cost, Proposal, Talk


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = '__all__'


class CostForm(forms.ModelForm):

    class Meta:
        model = Cost
        fields = ('sponsorship', 'value', 'reciprocity')


class ProposalForm(forms.ModelForm):

    class Meta:
        model = Proposal
        fields = ('description', 'value', 'quantity')


class TalkForm(forms.ModelForm):

    class Meta:
        model = Talk
        fields = ('date', 'start', 'description')

myproject/core/views.py
import json
from pprint import pprint
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView
from .models import Event
from .forms import EventForm, CostForm, ProposalForm, TalkForm


def index(request):
    return render(request, 'index.html')


event_detail = DetailView.as_view(
    model=Event,
    template_name='event_detail.html'
)


event_report = DetailView.as_view(
    model=Event,
    template_name='event_print.html'
)


@csrf_exempt
def event_add(request):
    event_data = json.loads(request.POST.get('event'))
    form = EventForm(event_data)

    if form.is_valid():
        obj = form.save()
        # retorna dados serializados
        data = form.data
        data['pk'] = obj.pk
        data['status_code'] = 200

        costs_data = json.loads(request.POST.get('costs'))
        if costs_data:
            for cost in costs_data:
                if cost.get('reciprocity'):
                    cost_form = CostForm(cost)
                    if cost_form.is_valid():
                        cost_post = cost_form.save(commit=False)
                        cost_post.event = obj
                        cost_post.save()

        proposals_data = json.loads(request.POST.get('proposals'))
        if proposals_data:
            for proposal in proposals_data:
                if proposal.get('description'):
                    proposal_form = ProposalForm(proposal)
                    if proposal_form.is_valid():
                        proposal_post = proposal_form.save(commit=False)
                        proposal_post.event = obj
                        proposal_post.save()

        talks_data = json.loads(request.POST.get('talks'))
        if talks_data:
            for talk in talks_data:
                if talk.get('date'):
                    talk_form = TalkForm(talk)
                    if talk_form.is_valid():
                        talk_post = talk_form.save(commit=False)
                        talk_post.event = obj
                        talk_post.save()
    else:
        data = form.errors
        data['status_code'] = 500

    return JsonResponse(data)

myproject/core/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Capoeira {%block title%}{%endblock%}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{%static '/css/styleindex.css'%}">

  <link rel="stylesheet" href="{%static '/css/style.css'%}">

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <!-- <script src="{ static 'js/jquery.validate.min.js'%}"></script> -->
  <!-- <script src="{ static 'js/jquery.mask.min.js'%}"></script> -->
  <!-- <script src="{ static 'js/localization/messages_pt_BR.js'%}"></script> -->

  <!-- Datepicker -->
  <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
  <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

  <!-- notify -->
  <!-- <script src="{ static 'js/bootstrap-notify.min.js' %}"></script> -->

  <!-- VueJS -->
  <script src="{% static '/js/vue.js' %}"></script>

  <!-- Axios -->
  <script src="{% static '/js/axios.min.js' %}"></script>

  {% block style %}{% endblock style %}
</head>

<body>
  <div id="app">

    <div class="container-fluid">
      {% block nav %}
        <!-- { include "nav.html" %} -->
      {% endblock nav %}

      <!-- Breadcrumb-->
      <!-- <ol class="breadcrumb breadcrumb-mt">
          <li class="breadcrumb-item">
              <a href="">Início</a>
          </li>
          {% block breadcrumbs %}{% endblock %}
      </ol> -->
    
      {% block content %}{% endblock content %}
      <!-- <footer class="footer mt-auto py-3">
        <p>Sistema ARI</p>
      </footer> -->
    </div>

  {% block js %}{% endblock js %}

  </div>

  {% block vuejs %}{% endblock vuejs %}

</body>

</html>

myproject/core/templates/event_detail.html
{% extends "base.html" %}
{% block title %}| Evento{%endblock%}
{% block style %}
<style>
  .glyphicon {  margin-bottom: 10px;margin-right: 10px;}
    small {
      display: block;
      line-height: 1.428571429;
      color: #999;
    }
  </style>
{% endblock style %}
{% block content %}
<div class="">
  <div class="accordion accordion-icons" id="accordionExample">
    <div class="card">
      <div class="card-header" id="headingOne" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <h2 class="mb-0">
          <button class="btn btn-link" type="button">
            <span><i class="fa fa-chevron-up"></i></span>
            Detalhes
          </button>
          <a class="btn btn-primary float-right" href="{% url 'core:event_report' object.pk %}">Imprimir</a>
        </h2>
      </div>
      <div id="collapseOne" class="my-collapse collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
        <div class="card-body">
          <div class="row row-cols-1 row-cols-md-3">
            <div class="col-sm-6 text-left mb-4">
              <div class="card">
                <div class="card-body">
                  <div class="well well-sm">
                    <div class="row">
                      <!-- poderia ser col-sm-6 -->
                      <div class="col-sm-12 col-md-12">
                        <ul class="list-group list-group-flush">
                          <li class="list-group-item"><b>Nome do evento</b> <br>{{ object.title }}</li>
                          <li class="list-group-item"><b>Sumário Executivo</b> <br>{{ object.executive_summary }}</li>
                          <li class="list-group-item"><b>Histórico da Instituição</b> <br>{{ object.institution_history }}</li>
                          <li class="list-group-item"><b>Histórico da modalidade / conceito do projeto</b> <br>{{ object.sport_history }}</li>
                          <li class="list-group-item"><b>Data do evento</b> <br>{{ object.date }}</li>
                          <li class="list-group-item"><b>Público estimado</b> <br>{{ object.estimated_audience }}</li>
                          <li class="list-group-item"><b>Local do evento</b> <br>{{ object.location }}</li>
                          <li class="list-group-item"><b>Horário do evento</b> <br>{{ object.start }}</li>
                          <li class="list-group-item"><b>Objetivo</b> <br>{{ object.objective }}</li>
                          <li class="list-group-item"><b>Inscrição</b> <br>{{ object.subscription }}</li>
                          <li class="list-group-item"><b>Forma de pagamento</b> <br>{{ object.payment }}</li>
                          <li class="list-group-item"><b>Imagem positiva x imagem corporativa</b> <br>{{ object.positive_image }}</li>
                          <li class="list-group-item"><b>Parceiros</b> <br>{{ object.partners }}</li>
                          <li class="list-group-item"><b>Custo x beneficio</b> <br>{{ object.description }}</li>
                          <li class="list-group-item"><b>Público-alvo</b> <br>{{ object.target_audience }}</li>
                          <li class="list-group-item"><b>Estratégias de marketing</b> <br>{{ object.marketing }}</li>
                          <li class="list-group-item"><b>Vantagens para o patrocinador</b> <br>{{ object.benefits }}</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- <ul class="list-group list-group-flush">
                  <li class="list-group-item">
                    <h5>lorem</h5>
                    <p class="card-text">lorem</p>
                    <p class="card-text">lorem</p>
                  </li>
                </ul> -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Cotas -->
    <div class="card">
      <div class="card-header" id="headingTwo" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <h2 class="mb-0">
          <button class="btn btn-link collapsed" type="button">
            <span><i class="fa fa-chevron-down"></i></span>
            Custo x Benefício
            <!-- <span>
              <i class="fa fa-plus fa-2x add-item" data-toggle="modal" data-target="#modalAdicionarOcorrencia" @click="getAddOcorrencia"></i>
            </span> -->
          </button>
        </h2>
      </div>
      <div id="collapseTwo" class="my-collapse collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Patrocínio</th>
                <th>Valor</th>
                <th>Reciprocidade</th>
                <!-- <th>Ações</th> -->
              </tr>
            </thead>
            <tbody>
              {% for cost in object.events.all %}
              <tr>
                <td>{{ cost.sponsorship }}</td>
                <td>{{ cost.value }}</td>
                <td>{{ cost.reciprocity }}</td>
                <!-- <td>
                  <span class="span-is-link" data-toggle="modal" data-target="#modalEditCost" click="getCost('{ url 'core:' cost.pk %}')">
                    <i class="fa fa-edit" style="margin-left: 10px;"></i>
                  </span>
                </td>
              </tr> -->
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- Orçamento -->
    <div class="card">
      <div class="card-header" id="heading3" data-toggle="collapse" data-target="#collapse3" aria-expanded="false" aria-controls="collapse3">
        <h2 class="mb-0">
          <button class="btn btn-link collapsed" type="button">
            <span><i class="fa fa-chevron-down"></i></span>
            Orçamento
          </button>
        </h2>
      </div>
      <div id="collapse3" class="my-collapse collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Descrição</th>
                <th>Valor Unitário</th>
                <th class="text-center">Quantidade</th>
                <th>Total</th>
                <!-- <th>Ações</th> -->
              </tr>
            </thead>
            <tbody>
              {% for proposal in object.proposal_events.all %}
              <tr>
                <td>{{ proposal.description }}</td>
                <td>R$ {{ proposal.value }}</td>
                <td class="text-center">{{ proposal.quantity }}</td>
                <td>R$ {{ proposal.get_subtotal }}</td>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <td colspan="2"></td>
                <td><b>Total Geral</b></td>
                <td>R$ {{ object.get_total }}</td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
    <!-- Evento -->
    <div class="card">
      <div class="card-header" id="heading4" data-toggle="collapse" data-target="#collapse4" aria-expanded="false" aria-controls="collapse4">
        <h2 class="mb-0">
          <button class="btn btn-link collapsed" type="button">
            <span><i class="fa fa-chevron-down"></i></span>
            Evento
          </button>
        </h2>
      </div>
      <div id="collapse4" class="my-collapse collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Data</th>
                <th>Hora</th>
                <th>Atividade</th>
                <!-- <th>Ações</th> -->
              </tr>
            </thead>
            <tbody>
              {% for talk in object.talk_events.all %}
              <tr>
                <td>{{ talk.date }}</td>
                <td>{{ talk.start }}</td>
                <td>{{ talk.description }}</td>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block vuejs %}
<script>
$('.my-collapse').on('shown.bs.collapse', function() {
  $(this).prev().find(".fa").addClass('fa-chevron-up').removeClass('fa-chevron-down');
});

$('.my-collapse').on('hidden.bs.collapse', function() {
  $(this).prev().find(".fa").addClass('fa-chevron-down').removeClass('fa-chevron-up');
});
</script>
<script>
const endpoint = '{{ endpoint }}';

axios.defaults.xsrfHeaderName = 'X-CSRFToken'
axios.defaults.xsrfCookieName = 'csrftoken'

var app = new Vue({
  el: '#app',
  delimiters: ['${', '}'],
});
</script>
{% endblock vuejs %}

myproject/core/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}| Evento{%endblock%}
{% block content %}
<div class="container">
  <h4>Adicionar Evento</h4>
  <form @submit.prevent="salvar">
    <div class="accordion" id="accordionExample">
      <!-- Evento -->
      <div class="card">
        <div class="card-header" id="heading1" data-toggle="collapse" data-target="#collapse1" aria-expanded="false" aria-controls="collapse1" @click="toggleCollapse(1)">
          <h2 class="mb-0">
            <button class="btn btn-link collapsed" type="button">
              <span>
                <i class="fa" :class="v.v1 ? 'fa-chevron-up' : 'fa-chevron-down'"></i>
              </span>
              Evento
            </button>
          </h2>
        </div>
        <div id="collapse1" class="my-collapse collapse show" aria-labelledby="heading1" data-parent="#accordionExample">
          <div class="card-body">
            <!-- Evento -->
            <div>
              <div class="form-group">
                <label for="" class="control-label required">Nome do evento</label>
                <input id="id_title" name="title" v-model="event.title" class="form-control" required type="text" />
              </div>
              <div class="form-group">
                <label for="" class="control-label">Sumário Executivo</label>
                <textarea id="id_executive_summary" name="executive_summary" v-model="event.executive_summary" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Histórico da Instituição</label>
                <textarea id="id_institution_history" name="institution_history" v-model="event.institution_history" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Histórico da modalidade / conceito do projeto</label>
                <textarea id="id_sport_history" name="sport_history" v-model="event.sport_history" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Data do evento</label>
                <input id="id_date" name="date" v-model="event.date" class="form-control" type="date" />
              </div>
              <div class="form-group">
                <label for="" class="control-label">Horário do evento</label>
                <input id="id_start" name="start" v-model="event.start" class="form-control" type="time" />
              </div>
              <div class="form-group">
                <label for="" class="control-label">Público estimado</label>
                <input id="id_estimated_audience" name="estimated_audience" v-model="event.estimated_audience" class="form-control" type="number" min="0" step="1" />
              </div>
              <div class="form-group">
                <label for="" class="control-label">Local do evento</label>
                <textarea id="id_location" name="location" v-model="event.location" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Objetivo</label>
                <textarea id="id_objective" name="objective" v-model="event.objective" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Inscrição</label>
                <textarea id="id_subscription" name="subscription" v-model="event.subscription" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Forma de pagamento</label>
                <textarea id="id_payment" name="payment" v-model="event.payment" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Imagem positiva x imagem corporativa</label>
                <textarea id="id_positive_image" name="positive_image" v-model="event.positive_image" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Parceiros do projeto</label>
                <textarea id="id_partners" name="partners" v-model="event.partners" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Custo x Beneficio</label>
                <textarea id="id_description" name="description" v-model="event.description" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Público-alvo</label>
                <textarea id="id_target_audience" name="target_audience" v-model="event.target_audience" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Estratégias de marketing</label>
                <textarea id="id_marketing" name="marketing" v-model="event.marketing" class="form-control" cols="30" rows="10"></textarea>
              </div>
              <div class="form-group">
                <label for="" class="control-label">Vantagens para o patrocinador</label>
                <textarea id="id_benefits" name="benefits" v-model="event.benefits" class="form-control" cols="30" rows="10"></textarea>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Cotas -->
      <div class="card">
        <div class="card-header" id="heading2" data-toggle="collapse" data-target="#collapse2" aria-expanded="false" aria-controls="collapse2" @click="toggleCollapse(2)">
          <h2 class="mb-0">
            <button class="btn btn-link collapsed" type="button">
              <span>
                <i class="fa" :class="v.v2 ? 'fa-chevron-up' : 'fa-chevron-down'"></i>
              </span>
              Cotas
            </button>
          </h2>
        </div>
        <div id="collapse2" class="my-collapse collapse" aria-labelledby="heading2" data-parent="#accordionExample">
          <div class="card-body">
            <div>
              <div class="form-row" v-for="cost in costs" :key="cost.id">
                <div class="form-group col-md-3">
                  <label class="control-label">Patrocínio</label>
                  <input :id="'cost_sponsorship'+cost.id" v-model="cost.sponsorship" class="form-control" type="text" />
                </div>
                <div class="form-group col-md-3">
                  <label class="control-label">Valor</label>
                  <input :id="'cost_value'+cost.id" v-model="cost.value" class="form-control" type="number" min="0" step="0.01" />
                </div>
                <div class="form-group col-md-6">
                  <label class="control-label">Reciprocidade</label>
                  <textarea :id="'cost_reciprocity'+cost.id" name="reciprocity" v-model="cost.reciprocity" class="form-control" cols="40" rows="10"></textarea>
                </div>
              </div> <!-- form-row -->
              <button id="btnCost" type="button" class="btn btn-primary" @click="costAdd">
                <i class="fa fa-plus"></i> Adicionar
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- Orçamento -->
      <div class="card">
        <div class="card-header" id="heading3" data-toggle="collapse" data-target="#collapse3" aria-expanded="false" aria-controls="collapse3" @click="toggleCollapse(3)">
          <h2 class="mb-0">
            <button class="btn btn-link collapsed" type="button">
              <span>
                <i class="fa" :class="v.v3 ? 'fa-chevron-up' : 'fa-chevron-down'"></i>
              </span>
              Orçamento
            </button>
          </h2>
        </div>
        <div id="collapse3" class="my-collapse collapse" aria-labelledby="heading3" data-parent="#accordionExample">
          <div class="card-body">
            <div>
              <div class="form-row" v-for="proposal in proposals" :key="proposal.id">
                <div class="form-group col-md-6">
                  <label class="control-label">Descrição</label>
                  <input :id="'proposal_description'+proposal.id" v-model="proposal.description" class="form-control" type="text" />
                </div>
                <div class="form-group col-md-3">
                  <label class="control-label">Valor Unitário</label>
                  <input :id="'proposal_value'+proposal.id" v-model="proposal.value" class="form-control" type="number" min="0" step="0.01" />
                </div>
                <div class="form-group col-md-3">
                  <label class="control-label">Quantidade</label>
                  <input :id="'proposal_quantity'+proposal.id" v-model="proposal.quantity" class="form-control" type="number" min="0" step="1" />
                </div>
              </div> <!-- form-row -->
              <button id="btnProposal" type="button" class="btn btn-primary" @click="proposalAdd">
                <i class="fa fa-plus"></i> Adicionar
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- Evento -->
      <div class="card">
        <div class="card-header" id="heading4" data-toggle="collapse" data-target="#collapse4" aria-expanded="false" aria-controls="collapse4" @click="toggleCollapse(4)">
          <h2 class="mb-0">
            <button class="btn btn-link collapsed" type="button">
              <span>
                <i class="fa" :class="v.v4 ? 'fa-chevron-up' : 'fa-chevron-down'"></i>
              </span>
              Eventos
            </button>
          </h2>
        </div>
        <div id="collapse4" class="my-collapse collapse" aria-labelledby="heading4" data-parent="#accordionExample">
          <div class="card-body">
            <div>
              <div class="form-row" v-for="talk in talks" :key="talk.id">
                <div class="form-group col-md-3">
                  <label for="" class="control-label">Data</label>
                  <input :id="'talk_date'+talk.id" name="date" v-model="talk.date" class="form-control" type="date" />
                </div>
                <div class="form-group col-md-3">
                  <label for="" class="control-label">Hora</label>
                  <input :id="'talk_start'+talk.id" name="start" v-model="talk.start" class="form-control" type="time" />
                </div>
                <div class="form-group col-md-6">
                  <label class="control-label">Atividade</label>
                  <input :id="'talk_description'+talk.id" v-model="talk.description" class="form-control" type="text" />
                </div>
              </div> <!-- form-row -->
              <button id="btnTalk" type="button" class="btn btn-primary" @click="talkAdd">
                <i class="fa fa-plus"></i> Adicionar
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="float-right mt-3">
      <button class="btn btn-lg btn-success" type="submit">Salvar</button>
    </div>
  </form>
</div>
{% endblock content %}
{% block vuejs %}
<script>
const endpoint = '{{ endpoint }}';
</script>
<script src="{% static 'js/event_add.js' %}"></script>
{% endblock vuejs %}